wandb_version: 1

learning-rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719699303
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.9
      5: 0.17.3
      8:
      - 4
      - 5
      13: darwin-arm64
